# Generated by Django 3.2.18 on 2023-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20230502_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted')], default='In Progress'),
        ),
    ]
